### ISSUE TITLE
Not pulling from postman API

### ISSUE THREAD

**Issue by hassanshaikley** [anthonyvscode/newman-action#431]
When I use

```
        with:
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          collection: ${{ secrets.POSTMAN_COLLECTION_URL }}
          reporters: cli
```

This doesn't work. It succeeds but I know it's not finding the collection.

I generate the collection url and api key when I hit share in postman

<img width="618" alt="Screen Shot 2023-01-23 at 2 06 28 PM" src="https://user-images.githubusercontent.com/6746840/214127800-209c14c0-796a-4398-ae23-1a7733b69536.png">

But I have no luck. It isn't finding the collection.
